const sliceName = "booking";

export const actionType = {
    SHOW_BANNERS: `${sliceName}/SHOW_BANNERS`,
    SHOW_LIST_MOVIE: `${sliceName}/SHOW_LIST_MOVIE`,
    SHOW_DANGCHIEU:`${sliceName}/SHOW_DANGCHIEU`,
    SHOW_SAPCHIEU:`${sliceName}/SHOW_SAPCHIEU`,
    SHOW_DETAIL_MOVIE:`${sliceName}/SHOW_DETAIL_MOVIE`,
    SHOW_SCHEDULE_MOVIE:`${sliceName}/SHOW_SCHEDULE_MOVIE`,
    SHOW_LIST_ROOM_TICKET:`${sliceName}/SHOW_LIST_ROOM_TICKET`,
    SET_BOOKING_TICKET:`${sliceName}/SET_BOOKING_TICKET`,
    SHOW_LIST_ROOM_TICKET_BOOKING:`${sliceName}/SHOE_LIST_ROOM_TICKET_BOOKING`,
    SHOW_LIST_ROOM_TICKET_BOOKED:`${sliceName}/SHOW_LIST_ROOM_TICKET_BOOKED`,
    SHOW_LIST_SCHEDULE_CINEMA:`${sliceName}/SHOW_LIST_SCHEDULE_CINEMA`
}