export const PATH_API = {
    LINK_BANNERS: '/api/QuanLyPhim/LayDanhSachBanner',
    LINK_lIST_MOVIE: '/api/QuanLyPhim/LayDanhSachPhimPhanTrang',
    LINK_DETAIL_MOVIE:'/api/QuanLyPhim/LayThongTinPhim',
    LINK_SCHEDULE_MOVIE:'/api/QuanLyRap/LayThongTinLichChieuPhim',
    LINK_ROOM_TICKET:'/api/QuanLyDatVe/LayDanhSachPhongVe',
    LINK_TICKKED:'/api/QuanLyDatVe/DatVe',
    LINK_LOGIN:'/api/QuanLyNguoiDung/DangNhap',
    LINK_PROFILE:'/api/QuanLyNguoiDung/ThongTinTaiKhoan',
    LINK_SCHEDULE_CINEMA:'/api/QuanLyRap/LayThongTinHeThongRap',
    LINK_SIGNUP:'/api/QuanLyNguoiDung/DangKy',
    LINK_MANAGER_FLIM:'/api/QuanLyPhim/LayDanhSachPhim',
    LINK_ADD_FILM:'/api/QuanLyPhim/ThemPhimUploadHinh',
    LINK_UPDATE_FILM:'/api/QuanLyPhim/CapNhatPhimUpload',   
    LINK_DELETE_FILM:'/api/QuanLyPhim/XoaPhim',
    LINK_ADD_SCHEDULE:'/api/QuanLyDatVe/TaoLichChieu',
    LINK_UPDATE_USER:'/api/QuanLyNguoiDung/CapNhatThongTinNguoiDung',
    LINK_LIST_USERS:'/api/QuanLyNguoiDung/LayDanhSachNguoiDung',
    LINK_DELETE_USER:'/api/QuanLyNguoiDung/XoaNguoiDung',
    LINK_ADD_USER:'/api/QuanLyNguoiDung/ThemNguoiDung',
    LINK_EDIT_UESR:'/api/QuanLyNguoiDung/CapNhatThongTinNguoiDung',
    LINK_INFOR_USER:'/api/QuanLyNguoiDung/LayThongTinNguoiDung',
   
}